services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb-inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress-inception
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    restart: always
    expose:
      - "${WORDPRESS_PORT:-9000}"
    networks:
      - inception
    
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx-inception
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    restart: always
    ports:
      - "${PORT:-443}:443"
    networks:
      - inception
  
networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind